# ------------------------------------------- #
# DATABASE CONFIGURATION                      #
# config/database.yaml                        #
# ------------------------------------------- #
# The key only accept :
#   production, development & test
# The value is an array of database configuration
# ------------------------------------------- #

production:
  # database driver
  driver: 'mysql'
  # database user
  username: 'username'
  # database password
  password: 'password'
  # database host
  host: 'localhost'
  # database port
  port: 3306
  # database name
  database: 'dbname'
  # database charset
  charset: 'utf8mb4'
  # database collation
  collation: 'utf8mb4_unicode_ci'
  # database migration table
  migration_table: 'migrations'
  # database prefix
  prefix: ''
  # database max pool
  pool: 20
development:
  # database driver
  driver: 'mysql'
  # database user
  username: 'username'
  # database password
  password: 'password'
  # database host
  host: 'localhost'
  # database port
  port: 3306
  # database name
  database: 'db_name_development'
  # database charset
  charset: 'utf8mb4'
  # database collation
  collation: 'utf8mb4_unicode_ci'
  # database migration table
  migration_table: 'migrations'
  # database prefix
  prefix: ''
  # database max pool
  pool: 20
test:
  # database driver
  driver: 'mysql'
  # database user
  username: 'username'
  # database password
  password: 'password'
  # database host
  host: 'localhost'
  # database port
  port: 3306
  # database name
  database: 'db_name_development'
  # database charset
  charset: 'utf8mb4'
  # database collation
  collation: 'utf8mb4_unicode_ci'
  # database migration table
  migration_table: 'migrations'
  # database prefix
  prefix: ''
  # database max pool
  pool: 20
